/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "blockcypherapi.h"
#include "btcaddress.h"
/* Header for class com_cryptowrist_AddressActivity */

#ifndef _Included_com_cryptowrist_AddressActivity
#define _Included_com_cryptowrist_AddressActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cryptowrist_AddressActivity
 * Method:    get_balance
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cryptowrist_AddressActivity_get_1balance
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_cryptowrist_AddressActivity
 * Method:    transaction
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cryptowrist_AddressActivity_transaction
  (JNIEnv *, jobject, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
