/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "webclient.h"
#include "blockcypherapi.h"
#include "btcaddress.h"
/* Header for class com_cryptowrist_MainActivity */

#ifndef _Included_com_cryptowrist_MainActivity
#define _Included_com_cryptowrist_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cryptowrist_MainActivity
 * Method:    load_str
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cryptowrist_MainActivity_load_1str
  (JNIEnv *, jobject);

BlockCypherAPI btc_api("da44ddd295714dcdaa27683072a4e8c3", BlockCypherAPI::API_Mode::TEST);

BtcSender address_1("mhBqrAQy1zaXNjALdHkCYzkxJmi3qUym6L",
		"03ccddeedabd5d23b495c8fe26449073f07d1d0cde9a68086ff813d13ee7e2447c",
		"e79ef6135fe2aa03e17b451ddcb2a1375b60b2331a9ec3196dff2d313818d1cf"
					);

BtcAddress address_2("mv4qGgzZFRV3Cd2HHQMmHrLNBoKheX7GQu");

#ifdef __cplusplus
}
#endif
#endif
