/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cryptowrist_MainActivity */

#ifndef _Included_com_cryptowrist_MainActivity
#define _Included_com_cryptowrist_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cryptowrist_MainActivity
 * Method:    load_str
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cryptowrist_MainActivity_load_1str
  (JNIEnv *, jobject);

/*
 * Class:     com_cryptowrist_MainActivity
 * Method:    create_address
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cryptowrist_MainActivity_create_1address
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
